### ISSUE TITLE
Rebuild kcolorchooser package on stable repo

### ISSUE THREAD

**Issue by varlesh** [manjaro/packages-plasma#2]
Sorry, i'm not found bug report page for others kde apps and write issue here.
Devs, please fix desktop-file kcolorchooser, because this freeze plasmashell or  Krunner.
Show bug here:
https://bugs.kde.org/show_bug.cgi?id=363051
Need remove one line on kcolorchooser.desktop:
`X-DBUS-StartupType=Multi`

**Comment by Kirek** [comment]
kcolorchooser is taken directly for archlinux, please report the bug there https://www.archlinux.org/packages/extra/x86_64/kcolorchooser/
